### ISSUE TITLE
Automatically building and publishing multi-arch releases using Github Actions

### ISSUE THREAD

**Issue by ssut** [ssut/payload-dumper-go#11]

**Comment by luk1337** [comment]
@ssut fyi, I managed to get Linux 386,x86_64,aarch64 + Windows 386,x86_64 working here — https://github.com/luk1337/payload-dumper-go/tree/1.0.2

**Comment by luk1337** [comment]
And also Linux armv7 here — https://github.com/luk1337/payload-dumper-go/tree/1.0.3

**Comment by luk1337** [comment]
darwin-amd64 — https://github.com/luk1337/payload-dumper-go/tree/1.0.4
