### ISSUE TITLE
[Feature Request] Ability to specify output directory

### ISSUE THREAD

**Issue by Cyber-Phantom** [ssut/payload-dumper-go#18]
Right now it just extracts in the working directory which is not something we always want. Having the ability to specific the output directory would be really useful.

**Comment by ssut** [comment]
I added support for specifying output directory via CLI flag `-output` or `-o`. Please check it.

**Comment by Cyber-Phantom** [comment]
I have just tested the new binary and i can confirm that it is working as intended. Thank You
