### ISSUE TITLE
Output flags aren't working [Windows]

### ISSUE THREAD

**Issue by Luffitys** [ssut/payload-dumper-go#20]
Using either -o or -output flags doesn't change the output path and uses the default ./extracted_* directory. Trying the -partitions flag doesn't work either.
Commands tried:
- payload-dumper-go.exe payload.bin -output exampledirectory
- payload-dumper-go.exe payload.bin -o exampledirectory
- payload-dumper-go.exe payload.bin -partitions system,vendor,system_ext,product

**Comment by FunctionalHacker** [comment]
Same here on Arch Linux

**Comment by luk1337** [comment]
You're meant to do:
```
payload-dumper-go.exe -output exampledirectory payload.bin
payload-dumper-go.exe -o exampledirectory payload.bin
payload-dumper-go.exe -partitions system,vendor,system_ext,product payload.bin
```

**Comment by Luffitys** [comment]
Above comment works perfectly on Windows. Issue closed
