### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by ForceGT** [ssut/payload-dumper-go#21]
Hey, it would be great if you can include the installation instructions 
Or would you accept a PR

I currently use Arch Linux and someone has already put the binary up on [Arch User Repository](https://aur.archlinux.org/packages/payload-dumper-go-bin/)
I can research about other Debian based Linux and Windows as well as Mac OS, regarding the installation steps

**Comment by osm0sis** [comment]
Go ahead and submit a PR...
