### ISSUE TITLE
android 12 rom error

### ISSUE THREAD

**Issue by qiurigao** [ssut/payload-dumper-go#23]
realme gt rmx2202 android 12

https://componentota-manual-cn.allawnfs.com/component-ota/21/10/17/8c89fffacdfe4f5b95bc576c10e0b15e.zip
![image](https://user-images.githubusercontent.com/22121479/138029313-e84bc330-0168-46b0-892b-94a27b24ff51.jpeg)

**Comment by luk1337** [comment]
@ssut close? He's not even using payload-dumper-go...

**Comment by ssut** [comment]
@luk1337 Thanks for letting me know. I am going to close this issue.
