### ISSUE TITLE
[Feature Request] Homebrew support

### ISSUE THREAD

**Issue by gGkAC3qfszbdViFkw4Fk9ooS2u** [ssut/payload-dumper-go#25]
It would be nice to see Homebrew support for this, similiar to Android Platform Tools. Not necessary due to the update frequency, but a nice to have considering the low level of maintenance.

https://docs.brew.sh/Cask-Cookbook
https://formulae.brew.sh/cask/android-platform-tools#default

**Comment by luk1337** [comment]
https://github.com/Homebrew/homebrew-core/pull/90781

**Comment by luk1337** [comment]
This is merged upstream ^^

**Comment by gGkAC3qfszbdViFkw4Fk9ooS2u** [comment]
Way too efficient. Thanks luk1137. :)
