### ISSUE TITLE
Specify type of checksum.

### ISSUE THREAD

**Issue by TipsyTheCat** [ssut/payload-dumper-go#27]
Can you please specify checksum type in "payload-dumper-go_[version]_checksum.txt" or in release description?

**Comment by luk1337** [comment]
https://goreleaser.com/customization/checksum/

**Comment by TipsyTheCat** [comment]
That does nothing to answer my question or solve the problem.

**Comment by usrDottik** [comment]
I think it does, the default algorithm is SHA256, and `goreleaser.yml` workflow does not specify a hashing algorithm, therefore it must be SHA256, and non other

**Comment by TipsyTheCat** [comment]
And now it's a PR (#28)
