### ISSUE TITLE
libzma-5.dll not found

### ISSUE THREAD

**Issue by 456vv** [ssut/payload-dumper-go#4]
libzma-5.dll not found

**Comment by Henrocker** [comment]
https://tukaani.org/xz/xz-5.2.5-windows.zip

Put this into payload-dumper executable folder.

**Comment by osm0sis** [comment]
Could be resolved by building payload-dumper-go for Windows as static I think.

**Comment by mmokrejs** [comment]
Either way, this should have been also documented in Requirements in README.md file ;-)
