### ISSUE TITLE
Can't get it to work on macos

### ISSUE THREAD

**Issue by WrathOP** [ssut/payload-dumper-go#43]
payload-dumper-go /path/to/payload.bin
zsh: exec format error: payload-dumper-go

getting this error I have set it as system path aswell in zshrc file

**Comment by luk1337** [comment]
You downloaded payload-dumper-go for the wrong CPU architecture?

**Comment by WrathOP** [comment]
no arm64 only I am on m1 mac

**Comment by luk1337** [comment]
`file $(which payload-dumper-go)` what does that say?

**Comment by WrathOP** [comment]
payload-dumper-go: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, BuildID[sha1]=8b9902f966324bf509a516aa5bc389823c5a4e15, for GNU/Linux 3.7.0, stripped
not:               cannot open `not' (No such file or directory)
found:             cannot open `found' (No such file or directory)

**Comment by luk1337** [comment]
So you downloaded payload-dumper-go for Linux instead of Darwin. Not surprising it doesn't work.

**Comment by WrathOP** [comment]
ohh macos is darwin i though its linux
