### ISSUE TITLE
Support arguments

### ISSUE THREAD

**Issue by Drugoy** [ssut/payload-dumper-go#46]
It'd be nice to be able run something like `payload-dumper-go info` (or `--dry-run`) to get just the info about the partitions and their sizes, like
```
payload.bin: payload.bin
Payload Version: 2
Payload Manifest Length: 229331
Payload Manifest Signature Length: 267
Found partitions:
my_engineering (336 kB), my_preload (2.5 MB), vendor_boot (201 MB), engineering_cdt (1.0 MB), keymaster (410 kB), system (705 MB), bluetooth (1.2 MB), uefisecapp (180 kB), imagefv (74 kB), abl (221 kB), my_bigball (808 MB), cpucp (188 kB), tz (3.9 MB), devcfg (49 kB), aop (278 kB), uefi (3.2 MB), vbmeta_system (8.2 kB), xbl (1.2 MB), recovery (105 MB), xbl_ramdump (832 kB), qupfw (57 kB), system_dlkm (348 kB), splash (332 kB), my_stock (965 MB), my_manifest (369 kB), system_ext (1.1 GB), my_region (3.9 MB), modem (298 MB), oplusstanvbk (2.0 MB), init_boot (8.4 MB), vbmeta (12 kB), boot (201 MB), product (2.9 MB), odm (1.5 GB), hyp (1.6 MB), vendor (1.1 GB), aop_config (16 kB), dtbo (25 MB), my_carrier (336 kB), xbl_config (192 kB), oplus_sec (852 kB), my_heytap (917 MB), dsp (67 MB), featenabler (98 kB), vendor_dlkm (145 MB), shrm (66 kB), my_company (336 kB), vbmeta_vendor (4.1 kB), my_product (553 MB)
```
It would also be nice to add a way to extract images for just the specified partition(s), like `payload-dumper-go --extract-partitions=init_boot,my_region` should extract just 2 small files and that operation should be damn fast.

**Comment by luk1337** [comment]
`payload-dumper-go -p init_boot,my_region payload.bin`

**Comment by Drugoy** [comment]
Disregard that ticket, the project just lacks the docs and I lacked curiosity at first.
The `-l`/`--list` and `-p`/`--partitions` args are already there, and I could learn that not only from reading the code, but also by running the util without any args...
