### ISSUE TITLE
Android version

### ISSUE THREAD

**Issue by ngocanhtve** [ssut/payload-dumper-go#47]
Hi,

I wonder if there is any way to use this software using Termux on Android system?

Thanks!

**Comment by luk1337** [comment]
Latest Linux arm64 prebuilt should work.

**Comment by ngocanhtve** [comment]
> Latest Linux arm64 prebuilt
You mean v1.2.2? I don't see any later prebuilds. Btw, how to use it on Android? Please guide me. Thanks a lot.

**Comment by luk1337** [comment]
just unzip and run it.

**Comment by ngocanhtve** [comment]
How exactly run it?

**Comment by luk1337** [comment]
./XXX where XXX is the executable name.

**Comment by luk1337** [comment]
chmod +x it.

**Comment by ngocanhtve** [comment]
Enough, stop here. Thank you for your every bit of enthusiasm.

**Comment by yuioto** [comment]
On Android, only certain paths can be granted executable permissions.
