### ISSUE TITLE
1.3.0 does not work on windows 7 now

### ISSUE THREAD

**Issue by daxiaamu** [ssut/payload-dumper-go#54]
<img width="333" alt="Snipaste_2024-12-24_05-25-05" src="https://github.com/user-attachments/assets/5641f12e-16a4-4cc2-9e89-cd185b0985d9" />
 
as above shows

And I test 1.2.1 in same envirenment, it works

**Comment by ssut** [comment]
This project currently uses Go v1.23, which is [provided by Fedora 41, the latest Fedora release at this time.](https://github.com/ssut/payload-dumper-go/blob/main/.github/workflows/goreleaser.yml#L34) As [Go discontinued support for Windows 7 starting from v1.21](https://github.com/golang/go/issues/57003), this project no longer supports Windows 7.

So I'm closing this issue as it falls outside the supported environments for the project.
